markdown: kramdown
kramdown:
    auto_ids: false
    syntax_highlighter_opts:
      disable : true

locales:
  # temporary workaround for new camp docs
  camp:
    path: /camp/
    lang: "Language"
    label:
      en: "english"
      de: "german"
      ru: "russian"
      fr: "french"
    nav:
      hoodieverse: "Hoodieverse"
      start: "Let's start"
      tutorials: "Tutorials"
      api: "API"
      plugins: "Plugins"
      deployment: "Deployment"
      community: "Community"
    menu:
      start: "Let's start"
      next: "Next Chapter"
      recipes: "Recipes"
    menuverse:
      welcome: "Welcome to Hoodie"
      concepts: "Hoodie Concepts"
      requirements: "Requirements"
      works: "How Hoodie works"
      glossary: "Glossary"
      next: "Let's start"
    menustart:
      installation: "Installation"
      started : "Getting started - pt1"
      next: "Tutorials"
    menututorials:
      started : "Getting started - pt2"
      timetracker: "time tracker"
      next: "API"
    menuapi:
      hoodie : "hoodie"
      account: "account"
      store : "store"
      task: "task"
      email: "email"
      global: "global share"
      next: "Plugins &amp; deployment"
    menuplugins:
      intro: "Intro"
      build: "Build your Plugin"
      api: "Plugin API"
      list: "List on npm"
      next: "Deployment"
    menudeploy:
      intro: "Intro"
      unix: "Unix / Linux"
      next: "Community"
    menucommunity:
      intro: "We are community"
      onboarding: "Onboarding"
      irc: "IRC office hours"
      workshop: "Hoodie workshop"
  en:
    path: /en/
    lang: "Language"
    label:
      en: "english"
      de: "german"
      ru: "russian"
      fr: "french"
    nav:
      hoodieverse: "Hoodieverse"
      start: "Let's start"
      tutorials: "Tutorials"
      api: "API"
      plugins: "Plugins"
      deployment: "Deployment"
      community: "Community"
    menu:
      start: "Let's start"
      next: "Next Chapter"
      recipes: "Recipes"
    menuverse:
      welcome: "Welcome to Hoodie"
      concepts: "Hoodie Concepts"
      requirements: "Requirements"
      works: "How Hoodie works"
      glossary: "Glossary"
      next: "Let's start"
    menustart:
      installation: "Installation"
      started : "Getting started - pt1"
      next: "Tutorials"
    menututorials:
      started : "Getting started - pt2"
      timetracker: "time tracker"
      next: "API"
    menuapi:
      hoodie : "hoodie"
      account: "account"
      store : "store"
      task: "task"
      email: "email"
      global: "global share"
      next: "Plugins &amp; deployment"
    menuplugins:
      intro: "Intro"
      build: "Build your Plugin"
      api: "Plugin API"
      list: "List on npm"
      next: "Deployment"
    menudeploy:
      intro: "Intro"
      unix: "Unix / Linux"
      next: "Community"
    menucommunity:
      intro: "We are community"
      onboarding: "Onboarding"
      irc: "IRC office hours"
      workshop: "Hoodie workshop"
  de:
    path: /de/
    lang: "Sprache"
    label:
      en: "englisch"
      de: "deutsch"
      ru: "russisch"
      fr: "französisch"
    nav:
      hoodieverse: "Hoodieverse"
      start: "Los geht's"
      tutorials: "Tutorials"
      api: "API"
      plugins: "Plugins"
      deployment: "Deployment"
      community: "Community"
    menu:
      start: "Los geht's"
      next: "Nächstes Kapitel"
      recipes: "Rezepte"
    menuverse:
      welcome: "Willkommen bei Hoodie"
      concepts: "Hoodie Konzepte"
      requirements: "Anforderungen"
      works: "Wie Hoodie funktioniert"
      glossary: "Glossar"
      next: "Los geht's"
    menustart:
      installation: "Installation"
      started : "Starten mit - Nr1"
      tutorials: "Tutorials"
      next: "Tutorials"
    menututorials:
      started : "Starten mit - Nr2"
      timetracker: "Zeitstopper"
      next: "API"
    menuapi:
      hoodie : "hoodie"
      account: "account"
      store : "store"
      task: "task"
      email: "email"
      global: "global share"
      next: "Plugins &amp; deployment"
    menuplugins:
      intro: "Einleitung"
      build: "Baue dein Plugin"
      api: "Plugin API"
      list: "Liste auf npm"
      next: "Deployment"
    menudeploy:
      intro: "Intro"
      unix: "Unix / Linux"
      next: "Community"
    menucommunity:
      intro: "Wir sind eine Community"
      onboarding: "Onboarding"
      irc: "IRC office Stunden"
      workshop: "Hoodie Workshop"

  ru:
    path: /ru/
    lang: "Язык"
    label:
      en: "английский"
      de: "немецкий"
      ru: "русский"
      fr: "французский"
    nav:
      hoodieverse: "Вселенная Hoodie"
      start: "Введение"
      tutorials: "Руководство"
      api: "API"
      plugins: "Плагины"
      deployment: "Внедрение"
      community: "Сообщество"
    menu:
      start: "Введение"
      next: "Следующая глава"
      recipes: "Рецепты"
    menuverse:
      welcome: "Добро пожаловать"
      concepts: "Концепция Hoodie"
      requirements: "Требования"
      works: "Как это работает"
      glossary: "Глоссарий"
      next: "Введение"
    menustart:
      installation: "Установка"
      started : "Начинаем работу с Hoodie, часть 1"
      next: "Руководство"
    menututorials:
      started : "Начинаем работу с Hoodie, часть 2"
      timetracker: "счетчик времени"
      next: "API"
    menuapi:
      hoodie : "hoodie"
      account: "account"
      store : "store"
      task: "task"
      email: "email"
      global: "global"
      next: "Плагины"
    menuplugins:
      intro: "Введение"
      build: "Пишем собственный плагин"
      api: "Plugin API"
      list: "Реестр npm"
      next: "Внедрение"
    menudeploy:
      intro: "Введение"
      unix: "Unix / Linux"
      next: "Сообщество"
    menucommunity:
      intro: "Мы &mdash; сообщество"
      onboarding: "Введение"
      irc: "Рабочее время IRC"
      workshop: "Мастер-класс Hoodie"
  fr:
    path: /fr/
    lang: "Langue"
    label:
      en: "anglais"
      de: "allemand"
      ru: "russe"
      fr: "français"
    nav:
      hoodieverse: "Hoodieverse"
      start: "Démarrage"
      tutorials: "Tutoriels"
      api: "API"
      plugins: "Plugins"
      deployment: "Déploiement"
      community: "Communauté"
    menu:
      start: "Démarrage"
      next: "Chapitre suivant"
      recipes: "Recette"
    menuverse:
      welcome: "Bienvenue chez Hoodie"
      concepts: "Concepts de Hoodie"
      requirements: "Prérequis"
      works: "Comment Hoodie fonctionne"
      glossary: "Glossaire"
      next: "Démarrage"
    menustart:
      installation: "Installation"
      started : "Démarrer avec Hoodie - partie 1"
      next: "Tutoriels"
    menututorials:
      started : "Démarrer avec Hoodie - partie 2"
      timetracker: "Gestion du temps"
      next: "API"
    menuapi:
      hoodie : "hoodie"
      account: "account"
      store : "store"
      task: "task"
      email: "email"
      global: "global share"
      next: "Plugins et déploiement"
    menuplugins:
      intro: "Intro"
      build: "Développer votre plugin"
      api: "L'API des plugins"
      list: "Liste sur npm"
      next: "Déploiement"
    menudeploy:
      intro: "Intro"
      unix: "Unix / Linux"
      next: "Communauté"
    menucommunity:
      intro: "Nous sommes une communauté"
      onboarding: "En voiture"
      irc: "Heures ouvrées IRC"
      workshop: "Atelier Hoodie"
